# Generated by Django 4.0.1 on 2022-01-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_list3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list3',
            name='code',
            field=models.TextField(),
        ),
    ]
