# Generated by Django 4.0.1 on 2022-01-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_list4'),
    ]

    operations = [
        migrations.CreateModel(
            name='List5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('code', models.TextField()),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('explanation', models.TextField()),
            ],
        ),
    ]
